### PR TITLE
V2.2.1

### PR DESCRIPTION
**Pull request by Limezy**
closes: #10 
closes: #12 
closes: #4

### CODE REVIEW

**Comment by Limezy** [comment]
!testme

**Comment by Limezy** [comment]
!testme

**Comment by Limezy** [comment]
!testme

**Comment by Limezy** [comment]
!testme

**Comment by Limezy** [comment]
!testme

**Comment by Limezy** [comment]
@ericgaspar I have rebased this branch with your commits on the other PR

**Comment by Limezy** [comment]
!testme

**Comment by silverhook** [comment]
@Limezy , I see you’ve gotten rid of the whole sandboxing block in the systemd part. That feels a bit excessive.

If you’re fed up with it, and it works now with the sandboxing off, I’d be willing to go do some trial-and-error-ing to figure out which sandboxing options can be (re-)enabled.

**Comment by Limezy** [comment]
@silverhook it is absolutely excessive, I fully agree. My strategy is usually to reach a "working" status and then improve.
I'm not an expert at all (even not a dev) so I have absolutely no clue about what part of the hardening code was breaking the package. Please feel very free to do some trials and errors, and I'll then merge that PR when you'll tell me. And please also tell me if the current version is working on your side ? Have you tried already ?

**Comment by ericgaspar** [comment]
Why not use `$data_dir` variable instead of `/home/yunohost.app/$app`?

**Comment by Limezy** [comment]
I'm not yet very familiar with v2 packaging.
1. I'm afraid of some automatic backup happening whereas we should distinguish between backing up `$data_dir/app`, which is the app, and backing up `$data_dir/repos`, which is the (big) data file associated to the app
2. I have seen somewhere in the docs that you can't use `$data_dir` as a user's home file, which is something necessary for this package to work, but I may be wrong ?

**Comment by silverhook** [comment]
> @silverhook it is absolutely excessive, I fully agree. My strategy is usually to reach a "working" status and then improve. I'm not an expert at all (even not a dev) so I have absolutely no clue about what part of the hardening code was breaking the package. Please feel very free to do some trials and errors, and I'll then merge that PR when you'll tell me.

OK, I’ll do that in the next two weeks, I hope (I’m a bit swamped right now)

> And please also tell me if the current version is working on your side ? Have you tried already ? On my side fully working in real world on my test server, reaching level 7 on the CI, and ready to merge.

I haven’t yet. Will give it a go.

**Comment by Limezy** [comment]
> OK, I’ll do that in the next two weeks, I hope (I’m a bit swamped right now)

No problem, but in that case I think I'll merge this PR and then let you enhance the hardening with a new one

@ericgaspar what about merging as is and then @silverhook could try cleaning by using `$data_dir` variable instead of `/home/yunohost.app/$app` ?

**Comment by silverhook** [comment]
That sounds sensible to me, yes.

**Pull request merged**
